In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"

In [7]:
import pandas as pd
df=pd.read_csv(url)
df.head()

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
df['price']=df["medv"]
df

        crim    zn  indus  chas    nox  ...  ptratio       b  lstat  medv  price
0    0.00632  18.0   2.31     0  0.538  ...     15.3  396.90   4.98  24.0   24.0
1    0.02731   0.0   7.07     0  0.469  ...     17.8  396.90   9.14  21.6   21.6
2    0.02729   0.0   7.07     0  0.469  ...     17.8  392.83   4.03  34.7   34.7
3    0.03237   0.0   2.18     0  0.458  ...     18.7  394.63   2.94  33.4   33.4
4    0.06905   0.0   2.18     0  0.458  ...     18.7  396.90   5.33  36.2   36.2
..       ...   ...    ...   ...    ...  ...      ...     ...    ...   ...    ...
501  0.06263   0.0  11.93     0  0.573  ...     21.0  391.99   9.67  22.4   22.4
502  0.04527   0.0  11.93     0  0.573  ...     21.0  396.90   9.08  20.6   20.6
503  0.06076   0.0  11.93     0  0.573  ...     21.0  396.90   5.64  23.9   23.9
504  0.10959   0.0  11.93     0  0.573  ...     21.0  393.45   6.48  22.0   22.0
505  0.04741   0.0  11.93     0  0.573  ...     21.0  396.90   7.88  11.9   11.9

[506 rows x 15 columns]

In [29]:
x=df.iloc[:,:-2]
y=df.iloc[:,-1]

In [32]:
from sklearn.model_selection import cross_val_score
lin_reg=LinearRegression()
mse=cross_val_score(lin_reg,X=x,y=y,scoring='neg_mean_squared_error')
mean_mse=np.mean(mse)
mean_mse

np.float64(-37.13180746769923)

In [37]:
rmse=np.sqrt(mean_mse)
rmse

array([3.52991509, 5.10378498, 5.75101191, 8.9867887 , 5.77179405])

In [28]:
#ridge regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()